[supervisord]
nodaemon=true
user=root

[program:mongo]
command=/bin/mongodb.sh
autostart=true
autorestart=false
stderr_logfile=/var/log/supervisor/mongo.err.log
stdout_logfile=/var/log/supervisor/mongo.out.log

[program:vault]
command=/bin/vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/vault.err.log
stdout_logfile=/var/log/supervisor/vault.out.log

[program:config]
command=/bin/vault-config.sh
autostart=true
autorestart=false
stderr_logfile=/var/log/supervisor/vault-config.err.log
stdout_logfile=/var/log/supervisor/vault-config.out.log

[program:vault-agent]
command=/bin/vault-agent.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/vault-agent.err.log
stdout_logfile=/var/log/supervisor/vault-agent.out.log
